version: "3.2"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:${SHADOWSOCKS_TAG}
    restart: unless-stopped
    ports:
      - protocol: tcp
        published: ${SHADOWSOCKS_PORT}
        target: 8388
      - protocol: udp
        published: ${SHADOWSOCKS_PORT}
        target: 8388
    environment:
      - PASSWORD=${SHADOWSOCKS_KEY}
      - METHOD=${SHADOWSOCKS_METHOD}
